CFLAGS = -W -pedantic -ansi -g 
UDPtimed: UDPtimed.c
	${CC} -o $@ ${CFLAGS} UDPtimed.c errexit.c

UDPtime: UDPtime.c
	${CC} -o $@ ${CFLAGS} UDPtime.c errexit.c

TCPecho: TCPecho.c
	${CC} -o $@ ${CFLAGS} TCPecho.c errexit.c

TCPechod: TCPechod.c
	${CC} -o $@ ${CFLAGS} TCPechod.c errexit.c
